### ISSUE TITLE
mmkv usage incompatible with expo in 3.1+

### ISSUE THREAD

**Issue by hishammalik** [kesha-antonov/react-native-background-downloader#16]
Library is no longer expo compatible with mmkv usage. This was an issue with react-native-mmkv (https://github.com/mrousavy/react-native-mmkv) but then expo compatibility was added in. See https://github.com/mrousavy/react-native-mmkv/issues/261. 

Please consider adding expo compatibility. Application crashes with error java.lang.UnsatisfiedLinkError. Following is the log trace

04-23 13:01:19.637  7038  7100 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:984)
04-23 13:01:19.637  7038  7100 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1562)
04-23 13:01:19.637  7038  7100 E AndroidRuntime: 	at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:226)
04-23 13:01:19.637  7038  7100 E AndroidRuntime: 	at com.tencent.mmkv.MMKV.initialize(MMKV.java:208)
04-23 13:01:19.637  7038  7100 E AndroidRuntime: 	at com.tencent.mmkv.MMKV.initialize(MMKV.java:94)
04-23 13:01:19.637  7038  7100 E AndroidRuntime: 	at com.eko.RNBackgroundDownloaderModule.<init>(RNBackgroundDownloaderModule.java:171)
04-23 13:01:19.637  7038  7100 E AndroidRuntime: 	at com.eko.RNBackgroundDownloaderPackage.createNativeModules(RNBackgroundDownloaderPackage.java:15)
04-23 13:01:19.637  7038  7100 E AndroidRuntime: 	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:43)
04-23 13:01:19.637  7038  7100 E AndroidRuntime: 	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
04-23 13:01:19.637  7038  7100 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1458)
04-23 13:01:19.637  7038  7100 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1429)
04-23 13:01:19.637  7038  7100 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1331)
04-23 13:01:19.637  7038  7100 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.lambda$runCreateReactContextOnNewThread$2(ReactInstanceManager.java:1101)
04-23 13:01:19.637  7038  7100 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.$r8$lambda$AwGS8CysOZmWJw3kRVARHQvw9Ew(ReactInstanceManager.java)
04-23 13:01:19.637  7038  7100 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$$ExternalSyntheticLambda5.run(D8$$SyntheticClass)
04-23 13:01:19.637  7038  7100 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)

**Comment by Houuse** [comment]
any solution for this?

**Comment by kesha-antonov** [comment]
Fixed

Try version `4.0.0-alpha.0`

https://www.npmjs.com/package/@kesha-antonov/react-native-background-downloader/v/4.0.0-alpha.0
